### ISSUE TITLE
Query about expected behaviour when running ALBA MT version

### ISSUE THREAD

**Issue by pellegri** [KevinCWLi/K600-ALBA#3]
This is Phil but on Luna's laptop.

I can currently compile and run the MT version of the code but the output looks as attached. It never seems to reach a command line for me to tell it to run events or anything else and I'm confused about what the code is expecting to happen. I'm also fairly convinced that this is because I don't understand what I'm supposed to be doing rather than anything with the code...

I note that the processor is running 100% of the time but I don't know if it's doing anything.

[runtime_output.txt](https://github.com/KevinCWLi/K600-ALBA/files/2839812/runtime_output.txt)

**Comment by pellegri** [comment]
Doh. It was just waiting until it had made the visual thing which we don't really want. Trying to suppress the visualisation stuff now.

**Comment by pellegri** [comment]
Soooo... it still seems to take a long time at the same point which I assume is due to the CADMesh stuff loading. I still don't understand what I need to do to run the code.

**Comment by paulpapka** [comment]
Luna,


If the geometry loads, it is ready for you. You need to implement your stuff in K600-ALBA/src/PrimaryGeneratorAction.cc

On the GEANT4 terminal type /run/beamOn 100 see what it does. Some trees are made, open click around on the leaves.


From what you find how particles are created, modify and see if what you modified does what you want.


Cheers


Paul


--------------------------------------------------
Department of Physics/Departement Fisika
1015 Merensky Building/-Gebou
Universiteit Stellenbosch University
Private Bag/Privaatsak X1,
Matieland, Stellenbosch 7602
South Africa/Suid-Afrika
Cell: +27 79 13 73 223 Tel: +27 21 808 3368
--------------------------------------------------
________________________________

**Comment by padsley** [comment]
OK. That seems to be working as expected. The long delay is due to the geometry loading?

Also, we're trying to run sans graphics so we're "just" waiting for the command-line prompt but that's taking a long time to appear. I've not seen it take so long before with GEANT4 which is why I was asking - I wasn't sure if it was running a batch file or something that I didn't know about.

OK. This seems fine.

**Comment by paulpapka** [comment]
I have been running 17 clovers + BGO's all done in CADmesh, it takes a good 20 minutes to load the geometry. I am not too sure what you are using in the simulations, but I guess what you are experiencing is because of the geometry loading.


--------------------------------------------------
Department of Physics/Departement Fisika
1015 Merensky Building/-Gebou
Universiteit Stellenbosch University
Private Bag/Privaatsak X1,
Matieland, Stellenbosch 7602
South Africa/Suid-Afrika
Cell: +27 79 13 73 223 Tel: +27 21 808 3368
--------------------------------------------------
________________________________

**Comment by padsley** [comment]
Great. That's perfect. Well, not perfect. But it explains the thing that was confusing me. Recommend closing the issue @KevinCWLi

**Comment by paulpapka** [comment]
I got used to it. Once the geometry is tested I usually switch all detectors off but one to implement the event generator. And only switch everything on before simulating the all thing.


--------------------------------------------------
Department of Physics/Departement Fisika
1015 Merensky Building/-Gebou
Universiteit Stellenbosch University
Private Bag/Privaatsak X1,
Matieland, Stellenbosch 7602
South Africa/Suid-Afrika
Cell: +27 79 13 73 223 Tel: +27 21 808 3368
--------------------------------------------------
________________________________

**Comment by KevinCWLi** [comment]
Paul is on it.
It is completely normal. It is because of the complexity of the meshes for the CLOVERs and the corresponding BGO Shields... it's actually the shields more than anything else. They are highly complex geometries and thus by implying the same level of "tolerance" (a metric for how bad a mesh relative to the original geometry), the file for the BGO shields becomes really large.
So yes, one just has to be patient with those. You can position the CLOVERS with just the actual CLOVER detectors without the shields to speed things up dramatically.

In principle, I can create much simpler meshes for people who want to check things quickly before running things with the proper geometry. This will be done after my PhD.
Unfortunately for now, one just has to be patient.

Kind regards
Kevin



On 07 Feb 2019, at 12:42 PM, paulpapka <notifications@github.com<mailto:notifications@github.com>> wrote:

I got used to it. Once the geometry is tested I usually switch all detectors off but one to implement the event generator. And only switch everything on before simulating the all thing.


--------------------------------------------------
Department of Physics/Departement Fisika
1015 Merensky Building/-Gebou
Universiteit Stellenbosch University
Private Bag/Privaatsak X1,
Matieland, Stellenbosch 7602
South Africa/Suid-Afrika
Cell: +27 79 13 73 223 Tel: +27 21 808 3368
--------------------------------------------------
________________________________

**Comment by padsley** [comment]
It's fine... it was mainly "Phil has broken it and isn't seeing what he expects from GEANT and is panicking". Who know that that was a thing...
